apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  annotations:
    litmuschaos.io/gitops: "true"
    litmuschaos.io/workflow: 8a4b7e13-a1d4-4f41-ac2b-45b4de4ab570
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.0
        ports:
        - containerPort: 8080
