apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  annotations:
    litmuschaos.io/gitops: "true"
    litmuschaos.io/workflow: aff9e816-df14-475d-8048-5bc4cc519dac
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.0
        ports:
        - containerPort: 8080
